### ISSUE TITLE
$tracks on line 77 throws a Notice.

### ISSUE THREAD

**Issue by daishan-swe** [nicolasbettag/LastFM-Played-for-Wordpress#3]
Hi!

Running:
Version 0.6
WordPress 4.1.1
PHP: 5.6.5

This is on a shared webhost, I get the following error:

Notice: Undefined variable: tracks in /path/to/wordpress/wp-content/plugins/lastfm-played-for-wp/index.php on line 77 Notice: Trying to get property of non-object in /path/to/wordpress/wp-content/plugins/lastfm-played-for-wp/index.php on line 77

Editing the index.php and putting a comment on line 77 solves this, and the plug-in works like a charm. Line 77 is a duplicate of line 98 BTW.

Example:
![image](https://cloud.githubusercontent.com/assets/11545048/6718713/e56c5c9c-cdb5-11e4-8def-a999ae3afe97.png)

**Comment by nicolasbettag** [comment]
Hey, should work now. Thanks! @daishan-swe
