### ISSUE TITLE
Update caused widget to scrable

### ISSUE THREAD

**Issue by pmh919** [nicolasbettag/LastFM-Played-for-Wordpress#5]
I did an update to your widget for www.919witt.org and now the screen is scrambled. Any help on fixing this?

I use Cornerstone to manage and have the widget in a 1/2 section of a row.

**Comment by nicolasbettag** [comment]
Hi there, I see. Let me figure out a solution - gonna update it asap.

**Comment by nicolasbettag** [comment]
Try the latest version, which I recently uploaded.

**Comment by pmh919** [comment]
That did it!

Thanks

**Comment by pmh919** [comment]
Actually Nic,

It went back to being messed up.

**Comment by nicolasbettag** [comment]
Is there a chance, that you'll contact me on Facebook? 
https://www.facebook.com/nicolasbettag

**Comment by pmh919** [comment]
Sorry Nicolas, I actually don't have facebook any longer. Is there another
preferred method?

**Comment by nicolasbettag** [comment]
Telegram?

**Comment by pmh919** [comment]
?
​

**Comment by nicolasbettag** [comment]
It's an messenger. Do you have any other favorite client?

**Comment by pmh919** [comment]
Typically I use skype.

**Comment by nicolasbettag** [comment]
What's ur nickname?

**Comment by pmh919** [comment]
bsupaul12

**Comment by nicolasbettag** [comment]
added.

**Comment by pmh919** [comment]
The same scrambling keeps occurring.

**Comment by pmh919** [comment]
Nic! I may have found my own error. The lastFM page I linked to no longer
need the "-" in between the Last.FM username. Orginally it was entered
"witt-fm" but now it works with "wittfm"

Thanks for your update!

**Comment by pmh919** [comment]
Actually never mind, the username is indeed "witt-fm"  It just started
working again however, odd?
