### ISSUE TITLE
Plugin not displaying properly.

### ISSUE THREAD

**Issue by kennybirdman** [nicolasbettag/LastFM-Played-for-Wordpress#6]
Hi Nicolas.
I seem to be having some issues with the plugin not displaying properly on my homepage. It has been working well until the latest update. I've tried entering other peoples usernames and it fixes the problem so it seems to be just my username which is strange. Here's the site -

http://kennybirdman.com

**Comment by nicolasbettag** [comment]
Hi @kennybirdman,

I reverted to the old version now. There were some problems with flexbox in many themes.
I'm working currently on version 1.0, which isn't beta/alpha/whatever anymore.

Stay tuned! 👍

**Comment by nicolasbettag** [comment]
Maybe @vinzlj wants to merge his fork. It's pretty nice.
