### ISSUE TITLE
The now playing information...

### ISSUE THREAD

**Issue by LordFader** [nicolasbettag/LastFM-Played-for-Wordpress#8]
Greetings.
Thank you very much for your great work with this plug in.
Since your last update the information about "**Now Playing**" is lost and it shows something like "48 years" instead "Now Playing" like you can check in the picture.
![image](https://user-images.githubusercontent.com/4002168/28745987-a78908fc-747b-11e7-9100-613ff2760035.png)
![image](https://user-images.githubusercontent.com/4002168/28746019-25cd2a5e-747c-11e7-987a-b1fc3868a743.png)
Can you tell me what I could doing wrong to give me this result?
Before the update all seems ok.
Thank you for your time.

**Comment by nicolasbettag** [comment]
Thanks for the bug report. I figured it out. Gonna release it in the next 10-20 minutes!

**Comment by nicolasbettag** [comment]
Published as v0.99.1! Check it out!

**Comment by LordFader** [comment]
Thx a lot is working fine.
